### ISSUE TITLE
Snake Game

### ISSUE THREAD

**Issue by Atif0604** [Dezenix/frontend-html-css-js#102]
### Description

I would like to add a snake game please assign me under swoc @thepranaygupta 

### Screenshots

https://user-images.githubusercontent.com/64218887/150291873-3dd9c3e5-5fcf-441a-a1b4-081810c40252.mp4

**Comment by nandini7637** [comment]
> ### Description
> I would like to add a snake game please assign me under swoc @thepranaygupta
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_

Add video reference to your game

**Comment by Atif0604** [comment]
> > ### Description
> > I would like to add a snake game please assign me under swoc @thepranaygupta
> > ### Screenshots
> > _No response_
> > ### Additional information
> > _No response_
> 
> Add video reference to your game

Added
