### ISSUE TITLE
Social media buttons

### ISSUE THREAD

**Issue by Sumandeep-Kaur** [Dezenix/frontend-html-css-js#116]
### Description

I would like to add these designs for social media icons.
Please assign me this under SWOC.

### Screenshots

![image](https://user-images.githubusercontent.com/77191007/151545460-a9fd25ed-bc7b-4868-b72a-888ee23be68f.png)
![image](https://user-images.githubusercontent.com/77191007/151545520-618646bd-72bc-48f3-965f-96e6f80e9349.png)
![image](https://user-images.githubusercontent.com/77191007/151545605-3007b769-a27b-441d-9249-b848acf3d210.png)
![image](https://user-images.githubusercontent.com/77191007/151545927-e07ed56b-6b21-4ebb-9fe3-e803fdb9f1b5.png)
![image](https://user-images.githubusercontent.com/77191007/151546549-c077f1bc-232c-4aa9-beab-fecf8d42477b.png)

**Comment by Utkarsh-190** [comment]
@Sumandeep-Kaur  I am SWOC participant and I want to work on this issue
