### ISSUE TITLE
Glassmorphism Form

### ISSUE THREAD

**Issue by siddhi-244** [Dezenix/frontend-html-css-js#12]
### Description

I would like to add Glassmorphism form component to this repository.  I am a participant of script winter of code.

**Comment by thepranaygupta** [comment]
> ### Description
> 
> I would like to add Glassmorphism form component to this repository. I am a participant of script winter of code.
> ### Screenshots
> 
> _No response_
> ### Additional information
> 
> _No response_

sure @siddhi-244 go for it. 🚀

**Comment by siddhi-244** [comment]
Please check my pr!

**Comment by thepranaygupta** [comment]
> Please check my pr!

According to the program guidelines no PRs should be accepted before Dec 11. 
@Ovenoboyo has [suggested some changes](https://github.com/Dezenix/frontend-html-css-js/pull/14#discussion_r764735961).
Also, avoid making your changes in the main branch, always create a new branch and make your desired changes in that branch.

**Comment by siddhi-244** [comment]
> > Please check my pr!
> 
> According to the program guidelines no PRs should be accepted before Dec 11. @Ovenoboyo has [suggested some changes](https://github.com/Dezenix/frontend-html-css-js/pull/14#discussion_r764735961). Also, avoid making your changes in the main branch, always create a new branch and make your desired changes in that branch.

Ok sure. Will do that.
