### ISSUE TITLE
Snake Game

### ISSUE THREAD

**Issue by Atif0604** [Dezenix/frontend-html-css-js#127]
### Description

Want to Add snake Game

### Screenshots

<img width="960" alt="Snake-Game" src="https://user-images.githubusercontent.com/64218887/159109090-642daa84-e638-41d8-8916-ff8c0a613828.png">

basically its a js based snake game and on eating up the fruits the snake become longer and score increases
### Additional information

Please assign me under GSSOC'22

**Comment by kashyap1905** [comment]
@Atif0604 Kindly add a preview of the game you wanted to add. and explain the game in short.

**Comment by Atif0604** [comment]
@kashyap1905

**Comment by Atif0604** [comment]
@Abirpal202049

**Comment by komalsoni4** [comment]
please assign it to me

**Comment by Atif0604** [comment]
Hey @AyushSingh22 could you please assign me
