### ISSUE TITLE
Responsive Login & Signup Page.

### ISSUE THREAD

**Issue by kashyap1905** [Dezenix/frontend-html-css-js#129]
### Description

Create a responsive login and signup page as given in the preview video.

### Screenshots

https://user-images.githubusercontent.com/87887741/158015471-05b36f05-6c30-4006-8d09-4f0fbc43a7e3.mp4

### Additional information

Self verify your code and output and place the files in the correct folders.
Also follow the contribution guidelines and code of conduct of GSSOC'22.

**Comment by aditi10701** [comment]
I am interested in working with this issue! Kindly assign me.

**Comment by kashyap1905** [comment]
> I am interested in working with this issue! Kindly assign me.

@aditi10701 You have already assigned with an issue (Issue no - #128). Kindly complete that issue first then attempt for other one.

**Comment by aditi10701** [comment]
@kashyap1905 the issue no -#128 is not assigned to me. Can you please confirm once.

**Comment by kashyap1905** [comment]
> @kashyap1905 the issue no -#128 is not assigned to me. Can you please confirm once.

Sorry, it was my mistake. Got confused because of similar name.

This issue has been assigned to you. Try to complete the code within 5 - 7 days.

**Comment by kashyap1905** [comment]
Assigned to @aditi10701

**Comment by aditi10701** [comment]
Thankyou!
Can I get the required png files for the vector images?

**Comment by kashyap1905** [comment]
> Thankyou! Can I get the required png files for the vector images?

Use any relevant free image of your choice. Try to keep the image size to the minimum.

**Comment by aditi10701** [comment]
The assigned Issue is completed.
https://github.com/aditi10701/Login-Sign-Up.git

**Comment by kashyap1905** [comment]
> The assigned Issue is completed. https://github.com/aditi10701/Login-Sign-Up.git

Kindly create a pull request from your repository to dezenix repository. Then I will be able to review it.

**Comment by aditi10701** [comment]
Done!
KIndly review the same.
