### ISSUE TITLE
A food Website clone.

### ISSUE THREAD

**Issue by anmol20112000** [Dezenix/frontend-html-css-js#13]
I would like to code front-end work on a Food website clone. I will use animation and material design.Assign me this issue..

**Comment by thepranaygupta** [comment]
> I would like to code front-end work on a Food website clone. I will use animation and material design.Assign me this issue..

@anmol20112000 we do not need a complete clone/template of a website.
This repository consists only of small code snippets of individual components.

**Comment by anmol20112000** [comment]
> > I would like to code front-end work on a Food website clone. I will use animation and material design.Assign me this issue..
> 
> @anmol20112000 we do not need a complete clone/template of a website.
> This repository consists only of small code snippets of individual components.

Okay then, plzzz just give me the idea i will  surely on that....plzzzz

**Comment by thepranaygupta** [comment]
> > > I would like to code front-end work on a Food website clone. I will use animation and material design.Assign me this issue..
> > 
> > 
> > @anmol20112000 we do not need a complete clone/template of a website.
> > This repository consists only of small code snippets of individual components.
> 
> Okay then, plzzz just give me the idea i will surely on that....plzzzz

We'll be creating issues soon.
