### ISSUE TITLE
Designe OTP Verification Page 

### ISSUE THREAD

**Issue by Abirpal202049** [Dezenix/frontend-html-css-js#133]
### Description

- [ ] Create a separate folder named OTP Page
- [ ] Responsive Designe 
- [ ] Designe it for 6-8 digits of OTP
- [ ]  Use Illustrations 
- [ ] After completing send the link So, to get a idea before Merging

Follow the contribution guidelines and **Code Of Conduct**

**Comment by Debdeep1** [comment]
I want to work on this issue under GSSoC'22

**Comment by Abirpal202049** [comment]
Any body want to grab this issue Grab This Quick
