### ISSUE TITLE
Add Tic-tac-toe Game

### ISSUE THREAD

**Issue by Devansh-365** [Dezenix/frontend-html-css-js#137]
### Description

I have created a Tic-tac-toe Game. Can I add that?
Tech Stack: Html, CSS, Javascript

Here is a link: https://devansh-365.github.io/Tic--Tac--Toe-Game/

### Screenshots

![WhatsApp Image 2022-03-16 at 9 00 24 PM](https://user-images.githubusercontent.com/83155844/158627491-c8634054-32ec-4eb8-ad7e-06a810a84c0c.jpeg)

**Comment by Abirpal202049** [comment]
Put this under the Games Folder which is already created
