### ISSUE TITLE
Add a Typing Game 'Typer'

### ISSUE THREAD

**Issue by Rakesh9100** [Dezenix/frontend-html-css-js#140]
### Description

I have created a Typing Game which is very interesting. I want to add that. Can I ?

Tech Stacks :-- HTML, CSS, JavaScript

Working as a GSSOC,22 Contributor !!

### Screenshots

![Preview](https://user-images.githubusercontent.com/73993775/159072939-93c3ac6a-44f9-42f9-b533-bf9c331de3e4.png)

**Comment by Abirpal202049** [comment]
@Rakesh9100 Try to improve the UI and the color scheme

**Comment by Rakesh9100** [comment]
### Please check out now !! 

![Typer](https://user-images.githubusercontent.com/73993775/160272052-588fcd03-db1a-4afc-b3c0-ff47a93d63c5.png)
