### ISSUE TITLE
Add a NFT Preview Card 

### ISSUE THREAD

**Issue by Vedant-Jayesh-Oza** [Dezenix/frontend-html-css-js#141]
### What would you like to share?

I want to add the NFT preview card that I did to practice my HTML and CSS skills. Please assign me this issue, I am a GSSoC'22 participant.
I am adding some screenshots of it.

![image](https://user-images.githubusercontent.com/75005433/159123164-f090e14d-2828-4708-aab3-31637a132a5d.png)

![image](https://user-images.githubusercontent.com/75005433/159123198-61b0cabd-d09b-42d2-b4bd-999d4aa93c6d.png)

**Comment by Abirpal202049** [comment]
If you can change the Theme and add animation to it then we can assign this issue

**Comment by Vedant-Jayesh-Oza** [comment]
Done with the recommended changes:- 

https://user-images.githubusercontent.com/75005433/159506876-26728c17-46ca-49d7-8cf6-3feb43f574b3.mp4

**Comment by Vedant-Jayesh-Oza** [comment]
Hey @Abirpal202049 Done with the changes:- 

https://user-images.githubusercontent.com/75005433/159507679-7ec1f472-e29f-4c0e-8c57-a9c5c2ba98ad.mp4

**Comment by Vedant-Jayesh-Oza** [comment]
Can I make a PR of this ?
