### ISSUE TITLE
Responsive Landing Page

### ISSUE THREAD

**Issue by saikatmu31** [Dezenix/frontend-html-css-js#144]
### Description

> Clean UI
> Maintain the Folder structure - Make a separate folder name Landing Page
> Share the link or image of your work when done
> Responsive Design

**Follow the contribution guidelines and Code Of Conduct**

### Screenshots

![Landing Page](https://user-images.githubusercontent.com/75084468/159960675-fc071a11-2a71-4f76-b49e-f55c54bf1dfb.jpg)

### Additional information

A sample image is provided don't copy it as it is. And try to complete the task as soon as possible (Preferably Within a Week)

**Comment by Aritra777** [comment]
I want to contribute to this issue under GSSOC'22.
please assign me.

**Comment by saikatmu31** [comment]
Ok, I'll Assign it to you, Best of Luck. Happy Coding.
