### ISSUE TITLE
Movie Search App 

### ISSUE THREAD

**Issue by Atif0604** [Dezenix/frontend-html-css-js#161]
### Description

It a js webapp that searches movie and give brief intro about the movie and rating

### Screenshots

<img width="943" alt="Movie-Search-App" src="https://user-images.githubusercontent.com/64218887/164067320-7e9b6f7a-57ea-4cf2-a31c-463712d11a3e.png">

**Comment by AyushSingh22** [comment]
I am assigning you this issue @Atif0604
