### ISSUE TITLE
Responsive FAQ accordin menu

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [Dezenix/frontend-html-css-js#162]
### What would you like to share?

I will be creating faq according using html, css, js. It will be helpful for websites.

### Additional information

![images.jpeg](https://user-images.githubusercontent.com/72568715/168133011-c4bcbdeb-e367-4bed-afcc-cd92b9175613.jpeg)

**Comment by Sulagna-Dutta-Roy** [comment]
@Abirpal202049 mentor, please assign me

**Comment by Sulagna-Dutta-Roy** [comment]
@Abirpal202049 Kindly assign me this Issue.

**Comment by Sulagna-Dutta-Roy** [comment]
@kashyap1905 @Jaideep25-tech kindly assign me this.

**Comment by Sulagna-Dutta-Roy** [comment]
Can I work on this Issue? Kindly assign me @AyushSingh22

**Comment by AyushSingh22** [comment]
Can you attach any screenshots for reference?

**Comment by AyushSingh22** [comment]
For now, I am assigning this to you. Start working !! @Sulagna-Dutta-Roy
