### ISSUE TITLE
To-do List app

### ISSUE THREAD

**Issue by Supriya2922** [Dezenix/frontend-html-css-js#165]
### What would you like to share?

I would like to create a to-do list app which will be responsive and will have internal web storage facility using HTML,CSS,JS.
Please assign me this issue as a GSSoC Contributor.

**Comment by AyushSingh22** [comment]
It would be better if you provide us a screenshot as a reference 
For now I am assigning you this issue. @Supriya2922

**Comment by AyushSingh22** [comment]
Kindly update @Supriya2922

**Comment by Sulagna-Dutta-Roy** [comment]
Can I work on this Issue?

**Comment by AyushSingh22** [comment]
Yes @Sulagna-Dutta-Roy
