### ISSUE TITLE
Random Password Generator

### ISSUE THREAD

**Issue by Jagroop2000** [Dezenix/frontend-html-css-js#166]
### Description

In this Webpage following feature's are added : 
 - Add an Input box where user can type the length of Password.
 - A Button  where on it's click a password is generated (Validations and Regular Expression is used to make it strong)
 
**Technology used :**
HTML , CSS , JavaScript , Bootstrap .

I also go through the repo  and i didn't found any project matched with it .

Please assign this enhancement to me .
Hoping Positive Response .

**Comment by AyushSingh22** [comment]
Start Working @Jagroop2000
