### ISSUE TITLE
Responsive IP Tracker using HTML, CSS and JS.

### ISSUE THREAD

**Issue by MonarchGitHub** [Dezenix/frontend-html-css-js#167]
### Description

I want to add an IP Tracker to the repo, this will be a good starter project for beginners to understand the working of API calls and responsive web design. 

### Screenshots

There are no screenshots available right now but I plan to create a very minimal and sleek design for this. I will add the screenshots as the project progresses.

**Comment by AyushSingh22** [comment]
Ok Go ahead @MonarchGitHub

**Comment by Sulagna-Dutta-Roy** [comment]
Can I work on this Issue?? @AyushSingh22

**Comment by AyushSingh22** [comment]
Yes @Sulagna-Dutta-Roy
