### ISSUE TITLE
Dice Roller Website

### ISSUE THREAD

**Issue by SupriyaGembali** [Dezenix/frontend-html-css-js#169]
### Description
This is a Dice Roller Website which shows a random number between 1 to 6, Accordingly changes the background color.
This generates a nice sound when dice are rolled

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by Srushti-Naik** [comment]
Dice rolls using JavaScript for web browser based games. Integrate it with basic HTML and CSS or any other means of graphical representation you wish to apply for displaying the dice and their values to the user.

Hello this is Srushti  GSSOC'22 participant please assign this issue to me.
