### ISSUE TITLE
Dark Mode (SWoC)

### ISSUE THREAD

**Issue by DragonUncaged** [Dezenix/frontend-html-css-js#17]
### Description

Description
I would like to add Dark Mode animation.
I am SWOC participant.

### Screenshots

![image](https://user-images.githubusercontent.com/72241207/145162033-d0676970-fe3f-4869-9f2b-1fc7a829c077.png)

![image](https://user-images.githubusercontent.com/72241207/145162073-295a9fe4-a4d8-411a-9429-6c239fc13972.png)

**Comment by garvitraj** [comment]
ig its not what we are looking for @DragonUncaged pls come up with something innovative
