### ISSUE TITLE
Google Shopping Website Clone

### ISSUE THREAD

**Issue by eswarbhageerath** [Dezenix/frontend-html-css-js#171]
### Description
This is the clone of the famous Website Google Shopping.

**Project title**
Google Shopping Website Clone

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

This is responsive in nature. 

This website folder has 2 components.

1.index.html
2.assets folder->CSS , JS and images

![image](https://user-images.githubusercontent.com/76146796/166207746-ed238f9c-b736-44e6-95df-7b1668cb02d5.png)

**Comment by komalsoni4** [comment]
please assign this issue to me
