### ISSUE TITLE
Coin tosser

### ISSUE THREAD

**Issue by eswarbhageerath** [Dezenix/frontend-html-css-js#173]
### What would you like to share?

This is a coin tosser website which tosses a coin when "TOSS" is clicked , various customizations are also available , like always head and always tails or fair throw.

**Comment by komalsoni4** [comment]
please assign this issue to me

**Comment by eswarbhageerath** [comment]
@komalsoni4 Actually, you have to create your own issue in the issues section. This is already assigned to me and it was merged too !!!! You have to ask the mentor of the repo to assign your issues to you. Hope you things clarified 😁

**Comment by eswarbhageerath** [comment]
@komalsoni4  You can make your own ideas according to the repo. And once any issue is assigned to you , you can start working on that issue , then after you have created a PR, once your PR is merged , you will have your score added in the GSSOC leaderboard.
