### ISSUE TITLE
Feedback UI component created with HTML CSS and Js

### ISSUE THREAD

**Issue by AmolShelke2** [Dezenix/frontend-html-css-js#177]
### Description

Hello project admin I'm a GSSOC participant and I want to add a feedback UI component project to the current repository it is a type of asking customers to give their feedback like they are happy neutral or satisfied with our services I'm adding the screenshot below to get you more concise of the project.

### Screenshots

![FeedBack UI Design - Google Chrome 10-05-2022 7 10 58 PM](https://user-images.githubusercontent.com/95171638/167643303-7d34fd6d-2a7c-4401-82a4-8df59a66b5ca.png)
![FeedBack UI Design - Google Chrome 10-05-2022 7 11 09 PM](https://user-images.githubusercontent.com/95171638/167643314-a3566f13-aa78-4404-a231-58dfed5b8cfc.png)

### Additional information

@Jaideep25-tech please review this issue.

**Comment by AyushSingh22** [comment]
**It's a Good Idea @AmolShelke2, Go ahead** 

Note: Create a separate folder and name it as Feedback Popups/forms so that other files with different UI and different ideas can be added to the folder.

**Comment by AmolShelke2** [comment]
Thank you ayush for assigning me the issue.
