### ISSUE TITLE
Adding 3d boxes project.

### ISSUE THREAD

**Issue by AmolShelke2** [Dezenix/frontend-html-css-js#179]
### Description

Hey project admin I want to add a 3d boxes project created with HTML CSS and JavaScript it is an animation project where we can click on a button to combine all the separate boxes into one big image 
I'm adding a demo below you can watch it.

### Screenshots

https://user-images.githubusercontent.com/95171638/168003219-27e783f6-a21d-44a0-a562-6030bfcb9d69.mp4

### Additional information

@AyushSingh22 please review this issue.

**Comment by AyushSingh22** [comment]
**Yes, You can go ahead with this project.**
@AmolShelke2 
Suggestion - Make it responsive enough !!

**Comment by AmolShelke2** [comment]
> **Yes, You can go ahead with this project.** @AmolShelke2 Suggestion - Make it responsive enough !!

Hey, @AyushSingh22 it is kindly difficult to make it responsive because the animation is taking the viewport width so I have tried to make it responsive but it doesn't happen. should I close this issue or create the pull request without responsiveness
