### ISSUE TITLE
Alarm Web Application

### ISSUE THREAD

**Issue by iamrahulmahato** [Dezenix/frontend-html-css-js#181]
### Description

I want to add an alarm application project created with HTML CSS and JavaScript  where you set alarm time and give notification of that exact time when you set the time

### Screenshots

![alarm](https://user-images.githubusercontent.com/49890655/168413141-22aa68f0-c351-4ae1-a288-0c8860bbd3be.png)

**Comment by komalsoni4** [comment]
please assign this issue to me
