### ISSUE TITLE
Contact form with animations.

### ISSUE THREAD

**Issue by AmolShelke2** [Dezenix/frontend-html-css-js#183]
### Description

Hey, Project admin I'm a GSSOC participant and I want to add a Contact form with some hover animations. it is created with HTML CSS and JavaScript. and I have used mostly hover effects on it. please assign me this issue to work on. I'm adding the preview of the project below once go through it. 

### Screenshots

https://user-images.githubusercontent.com/95171638/148639803-c85ee3a0-5b30-4b37-b086-d8c80df7d804.mp4

### Additional information

@AyushSingh22 please assign me this issue.
@Jaideep25-tech can I work on this issue.

**Comment by komalsoni4** [comment]
please assign this issue to me

**Comment by AmolShelke2** [comment]
> please assign this issue to me

@komalsoni4 I have created this issue please create another issue and ask the project admin to assign you.

**Comment by AyushSingh22** [comment]
@AmolShelke2 Foe now I am assigning you to work on this issue.
@komalsoni4 There are many opportunities you can create another animation, we will be happy to merge it.
