### ISSUE TITLE
Drag and Drop Uploads

### ISSUE THREAD

**Issue by RAHULBAWA777** [Dezenix/frontend-html-css-js#184]
### Description

Drag and Drop Uploads using html css js

### Screenshots

haven't started working on it yes .... awaiting for approval  :)

### Additional information

thus is my first contribution in this repo ...please tell me if any prerequisite if any

**Comment by komalsoni4** [comment]
Please assign this issue to me

**Comment by AyushSingh22** [comment]
@RAHULBAWA777 Would you like to be assigned to this issue?

**Comment by RAHULBAWA777** [comment]
> @RAHULBAWA777 Would you like to be assigned to this issue?

Yes
