### ISSUE TITLE
Food Panda Website Clone

### ISSUE THREAD

**Issue by eswarbhageerath** [Dezenix/frontend-html-css-js#185]
### Description
This is the clone of the famous Website Food Panda
**Project title**
Food Panda Website Clone

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

This is responsive in nature. 

This website folder has 2 components.

1.index.html
2.assets folder->CSS , JS and images

**Comment by komalsoni4** [comment]
@eswarbhageerath please assign this issue to me

**Comment by eswarbhageerath** [comment]
@komalsoni4 Actually, you have to create your own issue in the issues section. This is already assigned to me and it was merged too !!!! You have to ask the mentor of the repo to assign your issues to you. Hope you things clarified 😁.You can make your ideas according to the repo. And once any issue is assigned to you , you can start working on that issue , then after you have created a PR, once your PR is merged , you will have your score added in the GSSOC leaderboard.
Any doubts more, feel free to express. All the best.
