### ISSUE TITLE
O'Reilly UI

### ISSUE THREAD

**Issue by SupriyaGembali** [Dezenix/frontend-html-css-js#188]
### What would you like to share?

This project is  the clone of website O'Reilly.
Here I have used HTML, CSS, JavaScript.
![image](https://user-images.githubusercontent.com/94470209/168469415-bb59dabe-c186-4a5c-926c-725d1b9b05a3.png)

**Comment by komalsoni4** [comment]
@SupriyaGembali please assign this issue to me

**Comment by aditi10701** [comment]
Please assign this issue to me

**Comment by SupriyaGembali** [comment]
@aditi10701 You have to create your own issue in the issues section. You have to ask the mentor of the repo to assign your issues to you. Hope you things clarified .You can make your ideas according to the repo. After assigning , after you have worked on the Project , make a PR , after merging of PR, score will be added according to Level tag by mentor of repo.
Hope you are clear with the process in making issues and PRs.
