### ISSUE TITLE
Add Expand's card.

### ISSUE THREAD

**Issue by AmolShelke2** [Dezenix/frontend-html-css-js#194]
### Description

Hey, project admin, I'm a GSSOC participant and I want to add an Expanding card project created with HTML CSS and JavaScript. 
it is basically a type of slider project where we click on an image and it slides to the next image. I'm adding the preview below to get an idea of the project.

### Screenshots

https://user-images.githubusercontent.com/95171638/148639287-d9045b16-27d9-4de6-a9d0-cbe0df759f46.mp4

### Additional information

@AyushSingh22 can i work on this issue.

**Comment by AyushSingh22** [comment]
Yes Go ahead

**Comment by AmolShelke2** [comment]
> Yes Go ahead

@AyushSingh22 thanks for assigning this issue to me.
