### ISSUE TITLE
Stacked Cards

### ISSUE THREAD

**Issue by suyogkokaje** [Dezenix/frontend-html-css-js#20]
### Description

This is the design of cards. In this design initially, cards will be arranged in a stack and after we hover over that stack they will appear on the screen with proper animation. Also these cards will be responsive. The stack effect will only visible on desktop screen. On small screens stack effect will not be visible.

### Before Hover 
<img src="https://i.ibb.co/KhQVXSm/Screenshot-1384.png" alt="Screenshot-1384" border="0">

### After Hover
<img src="https://i.ibb.co/qmcc8bP/Screenshot-1385.png" alt="Screenshot-1385" border="0">

**Comment by suyogkokaje** [comment]
I would like add these cards. Could you please assign this work to me? I am SWOC participant.

**Comment by Abirpal202049** [comment]
Issue Solved
