### ISSUE TITLE
github User fetch adding.

### ISSUE THREAD

**Issue by AmolShelke2** [Dezenix/frontend-html-css-js#202]
### Description

Hey project admin, I'm a GSSOC participant and I want to add a Github user fetch app created with HTML CSS & JS. I have also used a third party API to get the GitHub users. and I have also handled errors if the user is not valid it will show the message that invalid user. I'm adding the preview below so you can get an idea of the project.

@AyushSingh22 can I work on this issue.

### Screenshots

![Technical Documentation Page - Google Chrome 17-05-2022 8 40 32 PM](https://user-images.githubusercontent.com/95171638/168846410-0fcf5376-2776-4345-a1a5-5a7c26c891cb.png)
![Technical Documentation Page - Google Chrome 17-05-2022 8 40 45 PM](https://user-images.githubusercontent.com/95171638/168846426-5a16308d-9eba-4d01-9296-b2cb291197d3.png)

**Comment by AyushSingh22** [comment]
Yeah, that's a good idea !
