### ISSUE TITLE
Interactive Animated  Login and Signup form 

### ISSUE THREAD

**Issue by RAHULBAWA777** [Dezenix/frontend-html-css-js#204]
### Description

adding a little tinch of css animation and  transition to typical boring login forms for users attraction 

### Screenshots

![image](https://user-images.githubusercontent.com/91609324/168890780-51c1821b-fe61-4abb-9ed4-dd05934746a3.png)

### Additional information

Stack - HTML CSS JS

**Comment by Jaideep25-tech** [comment]
done
