### ISSUE TITLE
Random Password Generator 

### ISSUE THREAD

**Issue by RAHULBAWA777** [Dezenix/frontend-html-css-js#209]
### Description

Add the length of password you want 
Add special characters/ number or a capital alphabet if you want ...just tick the desired option and hit enter ..... boom your in password is ready 

### Additional information

using HTML CSS JS

**Comment by RAHULBAWA777** [comment]
@Jaideep25-tech  bro ye bhi kr dena ... thank you

**Comment by RAHULBAWA777** [comment]
@AyushSingh22 kindly assign this  please...

**Comment by AyushSingh22** [comment]
Try to use the proper lines of sentences to describe your issues. @RAHULBAWA777
