### ISSUE TITLE
Img Filter App

### ISSUE THREAD

**Issue by Atif0604** [Dezenix/frontend-html-css-js#220]
### Description

A webapp that help you to edit your photos and apply custom filter

### Screenshots

<img width="960" alt="Image-Filter-App" src="https://user-images.githubusercontent.com/64218887/166492565-a71ab8a5-4482-42eb-b8c7-afd54c661e91.png">

**Comment by Atif0604** [comment]
@AyushSingh22 can you please assign

**Comment by AyushSingh22** [comment]
Can you add some more inforamtion or Screenshots ? @Atif0604

**Comment by Atif0604** [comment]
> Can you add some more inforamtion or Screenshots ? @Atif0604

https://user-images.githubusercontent.com/64218887/169471224-f89f965d-f7a4-430c-b1b0-6d0bc5c969b5.mp4
