### ISSUE TITLE
Google Homepage UI Clone

### ISSUE THREAD

**Issue by RAHULBAWA777** [Dezenix/frontend-html-css-js#221]
### Description

stack - html css js

### Screenshots

![image](https://user-images.githubusercontent.com/91609324/169475813-11158cd6-e706-4685-85a4-a6510399ba84.png)

### Additional information

@Jaideep25-tech @Abirpal202049  bhailog 3 din ho gye yrr mere 5 issue open he ... sorry to disturb you guys again but assign krne me 1minute hi lgta he .... if you guys are that busy .....
rank drop ho jayega bros .... varna me baar tag krke disturb nhi krta tumhe .... please assign ASAP :)

**Comment by RAHULBAWA777** [comment]
@AyushSingh22  bro please assign ... ive waited for so long

**Comment by AyushSingh22** [comment]
@RAHULBAWA777  Do not use these kinds of words, please refer to the Rules and regulations of GSSoC

**Comment by AyushSingh22** [comment]
Kindly write more descriptions to get this issue assigned to you.

**Comment by RAHULBAWA777** [comment]
> @RAHULBAWA777 Do not use these kinds of words, please refer to the Rules and regulations of GSSoC

ok apologies

**Comment by RAHULBAWA777** [comment]
> Kindly write more descriptions to get this issue assigned to you.

@AyushSingh22  it's a google homepage  UI clone 

https://user-images.githubusercontent.com/91609324/169592002-5076cb92-6f99-4ae3-b0da-4a47723bddeb.mp4
