### ISSUE TITLE
Circular Navigation Bar

### ISSUE THREAD

**Issue by suyogkokaje** [Dezenix/frontend-html-css-js#24]
### Description

At the beginning there will be a single button. After clicking on that all the options will be appear around that button in circular manner. If we again click on that button then options will disappear. All the options will appear and disappear with proper animation effect. 

## Before Clicking the button
<img src="https://i.ibb.co/wrct2Hk/Screenshot-1399.png" alt="Screenshot-1399" border="0">

## After Clicking the button
<img src="https://i.ibb.co/mbMcDcF/Screenshot-1402.png" alt="Screenshot-1402" border="0">

**Comment by suyogkokaje** [comment]
I would like to work on this navbar. Could you please assign this task to me?

**Comment by saikatmu31** [comment]
Okay @suyogkokaje  you can go ahead with this Task.

**Comment by komal1503** [comment]
I would like to work on this issue. could u please assign it to me @saikatmu31

**Comment by saikatmu31** [comment]
@komal1503  it is already assigned to @suyogkokaje you can find some other issue and work on it
