### ISSUE TITLE
Codegym Website Clone

### ISSUE THREAD

**Issue by eswarbhageerath** [Dezenix/frontend-html-css-js#241]
### Description

This is the clone of the famous Website Codegym

**Project title**
Codegym Website Clone

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

This is responsive in nature. 

### Screenshots

![image](https://user-images.githubusercontent.com/76146796/169690624-7debf139-35a4-4509-8ec4-6a30ab450ac3.png)

**Comment by eswarbhageerath** [comment]
@AyushSingh22 Why was this issue closed sir?

**Comment by AyushSingh22** [comment]
Because we have reviewed your code and we have approved it to merge. 
There are many PR and Issues so after approval and merge we close the respective issues.
@eswarbhageerath

**Comment by eswarbhageerath** [comment]
@AyushSingh22 Thank you, sir!
