### ISSUE TITLE
(glassmorphism) Digital Clock (SWoC) 

### ISSUE THREAD

**Issue by DragonUncaged** [Dezenix/frontend-html-css-js#26]
### Description

I would like to add Digital Clock animation.
I am SWOC participant.

I Have Completed This Project Already Completed This
If You Mark This as SWoC I will Create Pull request.

### Screenshots

![Digital-clock-demo](https://user-images.githubusercontent.com/72241207/146252407-6fdc10a0-3023-4cef-be37-98f42abbc393.gif)

**Comment by thepranaygupta** [comment]
> 

Go for it 👍
