### ISSUE TITLE
Navigation Menu

### ISSUE THREAD

**Issue by Sumandeep-Kaur** [Dezenix/frontend-html-css-js#29]
### Description

I would like to add one more style in navbar style components.

### Screenshots

https://user-images.githubusercontent.com/77191007/146640827-e358d96b-d7ee-4315-b5c1-bf74d3a22afe.mp4

**Comment by thepranaygupta** [comment]
okay, @Sumandeep-Kaur go ahead 👍
are you a SWoC participant?

**Comment by Sumandeep-Kaur** [comment]
> okay, @Sumandeep-Kaur go ahead 👍 are you a SWoC participant?

Yes, I'm SWOC participant.
