### ISSUE TITLE
Random Quote

### ISSUE THREAD

**Issue by 7ORP3DO** [Dezenix/frontend-html-css-js#30]
### Description

_I would like to add a Random Random Quote Generator._

### Screenshots

https://user-images.githubusercontent.com/80192140/146950317-8b7022d2-6d05-4d8a-967b-be1d850f3f75.mp4

**Comment by thepranaygupta** [comment]
@7ORP3DO assigned to you 👍 
are you a SWOC participant?

**Comment by 7ORP3DO** [comment]
> @7ORP3DO assigned to you 👍 are you a SWOC participant?

Thanks @thepranaygupta but i am not SWOC participant 😅.

**Comment by thepranaygupta** [comment]
> > @7ORP3DO assigned to you 👍 are you a SWOC participant?
> 
> Thanks @thepranaygupta but i am not SWOC participant 😅.

okay cool

**Comment by nandini7637** [comment]
@7ORP3DO what's the update on this?

**Comment by rishitajain01** [comment]
Can I work on this issue..?

**Comment by rishitajain01** [comment]
I am SWOC participant...and also 10 days of code participant.

**Comment by 7ORP3DO** [comment]
_@nandini7637, I apologize for late reply.  I have completed this project so now can I send pull request for it? Or  I have to wait or open a new issue?_

**Comment by nandini7637** [comment]
> I am SWOC participant...and also 10 days of code participant.

What's the update?

**Comment by nandini7637** [comment]
> _@nandini7637, I apologize for late reply. I have completed this project so now can I open a pull request for it? Or I have to wait or open a new issue?_

Wait for some time

**Comment by rishitajain01** [comment]
@nandini7637 working on it...I'll complete it soon..by the evening..

**Comment by rishitajain01** [comment]
@nandini7637 I have completed but facing some issue while pushing my files in the main branch..

**Comment by nandini7637** [comment]
> @nandini7637 I have completed but facing some issue while pushing my files in the main branch..

You have to make a PR, you can't directly push to main branch

**Comment by rishitajain01** [comment]
Yes I was facing problem in that only... I have sent you snapshot on discord.. Please have a look at that..
