### ISSUE TITLE
NPM Website Clone

### ISSUE THREAD

**Issue by eswarbhageerath** [Dezenix/frontend-html-css-js#308]
### Description

This is the clone of the website NPM. 

Here I have used HTML , CSS .

**Comment by AyushSingh22** [comment]
Alreday having this project , kindly check if yours is different, you can comment here we will assign. @eswarbhageerath

**Comment by eswarbhageerath** [comment]
Ok sir I will do that and I will open a new issue by doing so. Thank you sir 😁
