### ISSUE TITLE
Movie ticket grid with popup under modal

### ISSUE THREAD

**Issue by thepranaygupta** [Dezenix/frontend-html-css-js#32]
### Description

image assets:
* https://i.ibb.co/ThPNnzM/blade-runner.jpg
* https://i.ibb.co/Zd51z5c/justice-league.jpg

### Screenshots

https://user-images.githubusercontent.com/64855541/147125213-e51e404b-7a17-430f-ad94-1047ea20fc45.mp4

![image](https://user-images.githubusercontent.com/64855541/147125589-76f4d9ef-4a0c-4e75-bb06-af971607cd80.png)
![image](https://user-images.githubusercontent.com/64855541/147125597-acb12042-a2e8-49ae-9adb-329bdb902ca4.png)

**Comment by DGreat49251** [comment]
I WANT TO TAKE THIS ONE
