### ISSUE TITLE
Hover card UI effect

### ISSUE THREAD

**Issue by thepranaygupta** [Dezenix/frontend-html-css-js#33]
### Description

The card will have a **direction aware** hover effect and will turn to where the mouse pointer is moving giving it a cool 3D effect.

### Screenshots

https://user-images.githubusercontent.com/64855541/147126097-e2b31521-ff26-48ed-b875-eb2f606e625f.mp4

![image](https://user-images.githubusercontent.com/64855541/147126206-6b7ecec4-e512-4dc0-91f6-6aca1911c785.png)

**Comment by arpansharma-11** [comment]
I can work upon this.
