### ISSUE TITLE
Animated Event Timeline

### ISSUE THREAD

**Issue by nandini7637** [Dezenix/frontend-html-css-js#35]
### Description

Create a timeline similar to image below with scroll down animation effect

### Screenshots

![image](https://user-images.githubusercontent.com/76876383/147262613-805c39f6-9960-4570-9c75-9b9238340089.png)

**Comment by sohan9819** [comment]
Can I get the design file ?

**Comment by nandini7637** [comment]
> I can try it . Just have some doubts . Can I get the design file and can I use any css framework ? @nandini7637

I don't have it but you can design one and your element need not to be exact same as image, it's just for reference.
No you cannot use any css framework. @sohan9819

**Comment by sohan9819** [comment]
Ok thanks 👍

**Comment by sohan9819** [comment]
Is this ok @nandini7637 ?
![timeline](https://user-images.githubusercontent.com/64985447/147359354-8c35f255-f72c-40a2-a98e-e25bc9fd8778.png)

**Comment by nandini7637** [comment]
> Is this ok @nandini7637 ? ![timeline](https://user-images.githubusercontent.com/64985447/147359354-8c35f255-f72c-40a2-a98e-e25bc9fd8778.png)

Looks great! Add scroll down animation too

**Comment by sohan9819** [comment]
You want me to use gsap or something ?@nandini7637

**Comment by nandini7637** [comment]
> You want me to use gsap or something ?@nandini7637

No you can animate using js Or Jquery, don't use any library

**Comment by sohan9819** [comment]
do you have any reference for the animation ? @nandini7637

**Comment by nandini7637** [comment]
> do you have any reference for the animation ? @nandini7637
You can refer this video https://www.youtube.com/watch?v=7kOGCgUuCPY

**Comment by sohan9819** [comment]
ok thanks ! done 👍

https://user-images.githubusercontent.com/64985447/147371600-8a5f3256-8b81-42fc-9939-63eba4696841.mp4

@nandini7637
