### ISSUE TITLE
Text to speech converter in js

### ISSUE THREAD

**Issue by srinjoy-26** [Dezenix/frontend-html-css-js#355]
### Description

A program to convert text to speech using js.

### Screenshots

![Screenshot 2022-05-29 162006](https://user-images.githubusercontent.com/91176055/170864470-cf106eda-7654-49b4-bd33-0f907b5245f8.png)

**Comment by srinjoy-26** [comment]
@AyushSingh22 what level can I get on this issue

**Comment by AyushSingh22** [comment]
Level 3 @srinjoy-26

**Comment by srinjoy-26** [comment]
> Level 3 @srinjoy-26

Thanks bro 😁

**Comment by srinjoy-26** [comment]
> Level 3 @srinjoy-26

@AyushSingh22 bro please assign the new issues Ihve made , and merge this one
