### ISSUE TITLE
Simple Login form

### ISSUE THREAD

**Issue by nandini7637** [Dezenix/frontend-html-css-js#36]
### Description

Design a login form like the reference image.

### Screenshots

![image](https://user-images.githubusercontent.com/76876383/147316040-5301c4e8-4796-4e9c-9aec-779803c2a70e.png)

**Comment by Sumandeep-Kaur** [comment]
Hey @nandini7637, I would like to work on this. Please assign this issue to me! 
I'm SWOC participant.

**Comment by nandini7637** [comment]
Assigned it to you @Sumandeep-Kaur
