### ISSUE TITLE
Text animation

### ISSUE THREAD

**Issue by nandini7637** [Dezenix/frontend-html-css-js#40]
### Description

Design the animated text like reference video

### Screenshots

https://user-images.githubusercontent.com/76876383/147367185-51c6e2e5-6156-4242-8b98-f6e66f90b379.mp4

**Comment by sohan9819** [comment]
is this an svg text animation ? @nandini7637

**Comment by kashyap1905** [comment]
@nandini7637 Please assign this issue to me !

**Comment by nandini7637** [comment]
> is this an svg text animation ? @nandini7637

Nope

**Comment by kashyap1905** [comment]
@nandini7637 Can you please tell me in which folder I should put the files related to this issue??
