### ISSUE TITLE
Rotating Carousel

### ISSUE THREAD

**Issue by nandini7637** [Dezenix/frontend-html-css-js#41]
### Description

Design a responsive 360° rotating carousel

### Screenshots

https://user-images.githubusercontent.com/76876383/147367274-5e4832fc-9262-4799-9d37-9c8ce97dd705.mp4

**Comment by suyogkokaje** [comment]
Hello @nandini7637 we are supposed to make exact same carousel or we can add something more into it? Like we can reverse its rotation by dragging the mouse pointer in opposite direction. Also its view can be changed as per requirement. Like in this sample video we can see only front view. But it will be more beautiful if we get top view of the carousel as well.

**Comment by suyogkokaje** [comment]
I would like to work on this issue. Could you please assign this issue to me?
