### ISSUE TITLE
Simple Library Management

### ISSUE THREAD

**Issue by samipak458** [Dezenix/frontend-html-css-js#438]
### Description

A simple library management project that is easy to use and easy to understand as a beginner. I created this website while learning web development. I used all the basic concepts of JS in this project and I want to share my project to help other learners to understand the basic concepts of JS. I made this project using HTML, Bootstrap and JS.

### Screenshots

<p align="center">
<img src="https://user-images.githubusercontent.com/52650290/167833386-ec9951a2-fe1f-4c9b-88c9-2b7fe1ef6009.png">
<img src="https://user-images.githubusercontent.com/52650290/167833479-370a3485-2286-4eed-a7a8-57bb2c5411ed.png">
</p>

### Additional information

You can also see my project: [Online Library](https://delightful-coast-00b51a700.1.azurestaticapps.net/)

**Comment by samipak458** [comment]
@AyushSingh22 sir kindly assign me this issue, I'm GSSOC'22 contributor. My project is ready, I will create PR by next moment after assigning.

**Comment by sampavaranasi** [comment]
@AyushSingh22 @Jaideep25-tech Please complete these. Contributors may loose their score
