### ISSUE TITLE
Advanced Scientific Caluclator using C++

### ISSUE THREAD

**Issue by sampavaranasi** [Dezenix/frontend-html-css-js#461]
### Description

Advanced Scientific Calculator using C++

**Comment by sampavaranasi** [comment]
@Jaideep25-tech @AyushSingh22 Why don't you just at least reply? I have been tagging you guys since a day but I did not even get a proper response from you. Is there anything i am lagging behind in my issues or PRs , please let me know. But at least respond.

**Comment by AyushSingh22** [comment]
No as there are big numbers of PRs and issues we have to check, assign and merge we have lack of time to reply as it is the peak time if GSSoC'22. 
Sorry of inconvenience
@sampavaranasi
