### ISSUE TITLE
Responsive Accordion

### ISSUE THREAD

**Issue by nandini7637** [Dezenix/frontend-html-css-js#49]
### Description

Design an accordion with good color scheme, reference image given below.

### Screenshots

![image](https://user-images.githubusercontent.com/76876383/147399605-6bd94132-427e-49d2-8972-2ca10d89206a.png)

**Comment by Im-Abhi** [comment]
Hey can I work on this issue and can you provide more details about the questions and answers. Thank you. (SWOC-P)

**Comment by nandini7637** [comment]
> Hey can I work on this issue and can you provide more details about the questions and answers. Thank you. (SWOC-P)

You can use dummy text
