### ISSUE TITLE
Organize the File Structure

### ISSUE THREAD

**Issue by Abirpal202049** [Dezenix/frontend-html-css-js#50]
### Description

Put the "Circular Navbar" into the "Navbars" folder and all the Cards into "Product_Display_Cards"

**Comment by Im-Abhi** [comment]
Hey can I work on this issue. SWOC-Participant

**Comment by Abirpal202049** [comment]
Do you have understand the thing ?

**Comment by Im-Abhi** [comment]
If I'm not wrong then we just basically need to move the files/ folders to their respective places?

**Comment by Abirpal202049** [comment]
Yes

**Comment by Im-Abhi** [comment]
@Abirpal202049 please review the PR. Thank you
