### ISSUE TITLE
Music Player

### ISSUE THREAD

**Issue by nandini7637** [Dezenix/frontend-html-css-js#54]
### Description

Working music player with min 4 music tracks

### Screenshots

https://user-images.githubusercontent.com/76876383/147436373-1477911d-cb27-4ae8-934b-9f8791aea13a.mp4

**Comment by suyogkokaje** [comment]
I would like to work on this issue. Could you please assign this issue to me?

**Comment by ZaidKhan2002** [comment]
I would like to contribute for this.
