### ISSUE TITLE
Product Info Card Snippet

### ISSUE THREAD

**Issue by thepranaygupta** [Dezenix/frontend-html-css-js#59]
### Description

Product Info Card With Slideout Add to Cart, Colour and Size Tabs 

### Screenshots

https://user-images.githubusercontent.com/64855541/147500533-2e357d1e-ed84-426e-850a-f3c55ceae73d.mp4

### Additional information

Assets:
Image- 
![image](https://user-images.githubusercontent.com/64855541/147500629-dca90a85-a8a9-47ac-862f-d5dd0ec48e59.png)

**Comment by arpansharma-11** [comment]
I will contribute to this one

**Comment by DGreat49251** [comment]
I would like to take this one.

**Comment by thepranaygupta** [comment]
Assigned to @DGreat49251 👍
