### ISSUE TITLE
Product Display Card 3

### ISSUE THREAD

**Issue by thepranaygupta** [Dezenix/frontend-html-css-js#60]
### Description

A product display card with animated background using hover effect.

### Screenshots

https://user-images.githubusercontent.com/64855541/147501492-52e69d67-aadf-4ecb-b97e-d76e3633d320.mp4

### Additional information

Assets: [assets.zip](https://github.com/Dezenix/frontend-html-css-js/files/7781541/assets.zip)

**Comment by ZaidKhan2002** [comment]
Can I work on this ?

**Comment by Utkarsh-190** [comment]
I also want to work on this

**Comment by thepranaygupta** [comment]
> Can I work on this ?

@ZaidKhan2002 you can work on this 👍
