### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by nandini7637** [Dezenix/frontend-html-css-js#66]
### Description

Responsive Footer

### Screenshots

![image](https://user-images.githubusercontent.com/76876383/147756227-d4faf51a-7339-44bf-b1f3-f825333724b5.png)

**Comment by Sumandeep-Kaur** [comment]
I would like to work on this. Please assign this to me!

**Comment by kashyap1905** [comment]
@nandini7637 Can you please assign this to me !

**Comment by Sumandeep-Kaur** [comment]
@nandini7637 Can I use bootstrap or it should be in pure css?

**Comment by nandini7637** [comment]
> @nandini7637 Can I use bootstrap or it should be in pure css?
Pure css
