### ISSUE TITLE
Contact Us Form

### ISSUE THREAD

**Issue by nandini7637** [Dezenix/frontend-html-css-js#67]
### Description

Responsive Contact Us form

### Screenshots

![image](https://user-images.githubusercontent.com/76876383/147756689-69c513bd-9856-4ce0-a4e7-e11008b16129.png)

**Comment by suyogkokaje** [comment]
I would like to work on this issue. Could you please assign this issue to me?

**Comment by Arceus-sj** [comment]
I would like to work on this issue if this not resolve yet.
Could you assign this issue to me?
