### ISSUE TITLE
Game_01-Suduko game

### ISSUE THREAD

**Issue by nandini7637** [Dezenix/frontend-html-css-js#68]
### Description

Develop a responsive suduko game with easy, medium and hard levels.

**Comment by ssachis** [comment]
can I be assigned this issue?

**Comment by nandini7637** [comment]
@ssachis go ahead

**Comment by nandini7637** [comment]
@ssachis  the game should have easy, medium and difficult levels

**Comment by ssachis** [comment]
ok I will make that

**Comment by nandini7637** [comment]
> ok I will make that

@ssachis you have 3 more days else you will be unassigned

**Comment by ssachis** [comment]
will finish by tomm

**Comment by ssachis** [comment]
ok I have completed it

**Comment by ssachis** [comment]
https://ssachis.github.io/sudoku/

**Comment by ssachis** [comment]
should i make a pr now?

**Comment by ssachis** [comment]
I accidently unassigned myself

**Comment by ssachis** [comment]
in which folder should I add it?

**Comment by nandini7637** [comment]
Updates?

**Comment by ssachis** [comment]
yh i created a new pr since I had to change the location of the files
