### ISSUE TITLE
Game_02- Mind game 

### ISSUE THREAD

**Issue by nandini7637** [Dezenix/frontend-html-css-js#69]
### Description

Develop some Mind game as per your choice and creativity.

**Comment by Sumandeep-Kaur** [comment]
I would like to add memory game (a card game where you need to match pairs by turn over 2 cards at a time).

Here's preview example:
![Screenshot (2)](https://user-images.githubusercontent.com/77191007/147822800-86f25017-2eef-4f71-b22a-e0deb05c35a0.png)

**Comment by nandini7637** [comment]
> I would like to add memory game (a card game where you need to match pairs by turn over 2 cards at a time).
> 
> Here's preview example: ![Screenshot (2)](https://user-images.githubusercontent.com/77191007/147822800-86f25017-2eef-4f71-b22a-e0deb05c35a0.png)

You are already assigned an issue first compete that, then I'll assign you this

**Comment by sohan9819** [comment]
Can I go for this ?

**Comment by Sumandeep-Kaur** [comment]
> > I would like to add memory game (a card game where you need to match pairs by turn over 2 cards at a time).
> > Here's preview example: ![Screenshot (2)](https://user-images.githubusercontent.com/77191007/147822800-86f25017-2eef-4f71-b22a-e0deb05c35a0.png)
> 
> You are already assigned an issue first compete that, then I'll assign you this

I have made PR for that issue, can I work on this now?

**Comment by nandini7637** [comment]
@sohan9819 kindly provide the preview and the game should not be same as sumandeep's

**Comment by nandini7637** [comment]
@Sumandeep-Kaur you can start with your game

**Comment by Sumandeep-Kaur** [comment]
Can I add TIC TAC TOE game under this @nandini7637

**Comment by nandini7637** [comment]
> Can I add TIC TAC TOE game under this @nandini7637

The other player should be computer

**Comment by thepranaygupta** [comment]
@nandini7637 please add the level of this issue as a label

**Comment by nandini7637** [comment]
@Sumandeep-Kaur are you working on this issue?

**Comment by Sumandeep-Kaur** [comment]
> @Sumandeep-Kaur are you working on this issue?

Yes I'm working, actually I was down with fever that's why it was delayed. 
But will made PR by tomorrow!

**Comment by nandini7637** [comment]
> > @Sumandeep-Kaur are you working on this issue?
> 
> Yes I'm working, actually I was down with fever that's why it was delayed. But will made PR by tomorrow!

Oh no issues, take your time and get well soon :)
