### ISSUE TITLE
Custom Range Input Slider With Labels

### ISSUE THREAD

**Issue by thepranaygupta** [Dezenix/frontend-html-css-js#73]
### Description

This custom input range slider is awesome in many useful ways particularly a wide range of numbers that is equally available to the user, there is a known upper and lower limit to the range and the user is expected to “play” with their input, adjusting it frequently.

### Screenshots

![image](https://i0.wp.com/codemyui.com/wp-content/uploads/2015/09/custom-range-input-slider-with-labels.gif?fit=880%2C440&ssl=1)

**Comment by Nidhikumari-4** [comment]
please asign this issue to me.

**Comment by nandini7637** [comment]
> please asign this issue to me.

@Nidhikumari-4  updates?

**Comment by Nidhikumari-4** [comment]
yes I am working on it I will be submitting it soon @nandini7637

**Comment by kashyap1905** [comment]
@thepranaygupta @nandini7637 Please assign this issue to me.
