### ISSUE TITLE
0-200 Range Slider with Number Above Slider

### ISSUE THREAD

**Issue by thepranaygupta** [Dezenix/frontend-html-css-js#74]
### Description

This is a modern minimal range slider with a circle above the range indicator that shows the current number of the range as you slide it along. You can also click anywhere along the range slider to jump to that number. 

### Screenshots

![0-200-Range-Slider-with-Number-Above-Slider](https://user-images.githubusercontent.com/64855541/147945755-5a15fa12-dca5-4db4-ba12-c633649df701.gif)

**Comment by kashyap1905** [comment]
@thepranaygupta Please assign this issue to me.
