### ISSUE TITLE
Custom Input Field To Accept Numbers

### ISSUE THREAD

**Issue by thepranaygupta** [Dezenix/frontend-html-css-js#75]
### Description

This is something that you can use on your website where you want to take a numeric input from the user. You can use the plus and minus signs to increase or decrease the number. Alternatively, you can just click in the centre area and add a number by yourself. 

### Screenshots

![](https://i0.wp.com/codemyui.com/wp-content/uploads/2016/11/custom-input-field.gif?fit=880%2C440&ssl=1)

**Comment by rishitajain01** [comment]
@thepranaygupta please assign this to me.....I'm SWOC Contributor.

**Comment by nandini7637** [comment]
Updates?

**Comment by rishitajain01** [comment]
working on it...

**Comment by nandini7637** [comment]
> working on it...

Please be done in a day Or two

**Comment by Im-Abhi** [comment]
Can i work on this ?
