### ISSUE TITLE
Button to Email Subscription Field 

### ISSUE THREAD

**Issue by thepranaygupta** [Dezenix/frontend-html-css-js#76]
### Description

This button will expand into an email subscription field, it will be a great CTA on sites where you have limited space to work with.  

### Screenshots

![Button-to-Email-Subscription-Field](https://user-images.githubusercontent.com/64855541/147946198-02fe03e0-561c-4aba-aa7d-cbc13d71c0a3.gif)

**Comment by sakshi168** [comment]
@thepranaygupta  can you please assign this to me

**Comment by nandini7637** [comment]
Updates?

**Comment by geetika005** [comment]
Please assign this issue to me

**Comment by nandini7637** [comment]
@geetika005 I have reverted your PR, add readme and folder structure like other components in repo
