### ISSUE TITLE
Fullscreen Overlay Navigation Menu

### ISSUE THREAD

**Issue by thepranaygupta** [Dezenix/frontend-html-css-js#77]
### Description

A hamburger menu to fullscreen overlay navigation menu with hover effects.

### Screenshots

![](https://i0.wp.com/codemyui.com/wp-content/uploads/2015/12/fullscreen-overlay-navigation-menu.gif?fit=880%2C440&ssl=1)

**Comment by sohan9819** [comment]
can I try this ?
@thepranaygupta

**Comment by nandini7637** [comment]
> can I try this ? @thepranaygupta

are you a SWOC participant?

**Comment by sohan9819** [comment]
@nandini7637 
Can you please assign this issue to me ?

**Comment by nandini7637** [comment]
> @nandini7637 Can you please assign this issue to me ?

Was my question visible to you XD?

**Comment by sohan9819** [comment]
@nandini7637 Which one ?

**Comment by sohan9819** [comment]
here is my preview @thepranaygupta  @nandini7637 

https://user-images.githubusercontent.com/64985447/148068258-60707ce1-0a96-4a56-9b65-731bdbf07456.mp4

**Comment by nandini7637** [comment]
> here is my preview @thepranaygupta @nandini7637
> 
>  navbar.mp4

This issue is for SWOC participant, are you are participant in that?

**Comment by sohan9819** [comment]
@nandini7637 I guess I am not 😅

**Comment by nandini7637** [comment]
> @nandini7637 I guess I am not 😅

No issues since you have already worked on it but the issues with SWOC tag are only for the participants. Kindly take care from now-onwards

**Comment by sohan9819** [comment]
@nandini7637 Ok sure and thanks

**Comment by Im-Abhi** [comment]
Can I work on this issue (SWOC P)

**Comment by thepranaygupta** [comment]
> > @nandini7637 I guess I am not 😅
> 
> No issues since you have already worked on it but the issues with SWOC tag are only for the participants. Kindly take care from now-onwards

they can still contribute to the repo, since @sohan9819  was the first to respond I'm assigning the issue to him.
