### ISSUE TITLE
Expanding on hover animated Footer

### ISSUE THREAD

**Issue by nandini7637** [Dezenix/frontend-html-css-js#83]
### Description

Add a responsive footer in which social media sections expand on hover, reference image given below

### Screenshots

![image](https://user-images.githubusercontent.com/76876383/148552184-d46d68c9-f4b4-4ed7-bbae-917d426d7f0b.png)
<br>
![image](https://user-images.githubusercontent.com/76876383/148552200-18142973-dbd1-4097-b49f-92a1c2b501eb.png)

**Comment by Im-Abhi** [comment]
Can I work on this issue (SWOC-P)

**Comment by komal1503** [comment]
If this issue is still open...can I work on this? @nandini7637

**Comment by nandini7637** [comment]
@Im-Abhi updates?

**Comment by Im-Abhi** [comment]
It's almost done soon enough will be creating the PR for same.
