### ISSUE TITLE
Simple registration form

### ISSUE THREAD

**Issue by nandini7637** [Dezenix/frontend-html-css-js#84]
### Description

Make a responsive form with fields given in reference image:

### Screenshots

![image](https://user-images.githubusercontent.com/76876383/148552683-c9a19058-faac-4a16-9105-1560d80fcd5b.png)
<br>
![image](https://user-images.githubusercontent.com/76876383/148552728-28b8ddee-f61e-4e36-83e8-2db009228ef4.png)

**Comment by kashyap1905** [comment]
@nandini7637 @thepranaygupta Please assign this issue to me.
